 /*USE FictionalMuseum;
GO
INSERT INTO Country VALUES ('IT', 'Italy')
INSERT INTO Country VALUES ('GE', 'Germany')
INSERT INTO Country VALUES ('NE', 'Netherlands')
INSERT INTO Country VALUES ('US', 'United States')
INSERT INTO Country VALUES ('MX', 'Mexico')
INSERT INTO Country VALUES ('SP', 'Spain')
INSERT INTO Country VALUES ('UK', 'United Kingdom')
INSERT INTO Country VALUES ('FR', 'France')
INSERT INTO Country VALUES ('SW', 'Switzerland')

INSERT INTO Medium VALUES ('P', 'Painting')
INSERT INTO Medium VALUES ('S', 'Sculpture')
INSERT INTO Medium VALUES ('D', 'Drawing')
INSERT INTO Medium VALUES ('PH', 'Photography')
INSERT INTO Medium VALUES ('PR', 'Printmaking')

INSERT INTO Positions VALUES ('DIR', 'Director')
INSERT INTO Positions VALUES ('CUR', 'Curator')
INSERT INTO Positions VALUES ('ED', 'Exhibit Designer')
INSERT INTO Positions VALUES ('TG', 'Tour Guide')
INSERT INTO Positions VALUES ('INT', 'Intern')

INSERT INTO Artist VALUES (101, 'Michelangelo', 'IT')
INSERT INTO Artist VALUES (102, 'Vincent Van Gogh', 'NE')
INSERT INTO Artist VALUES (103, 'Albrecht Durer', 'GE')
INSERT INTO Artist VALUES (104, 'Frida Kahlo', 'MX')
INSERT INTO Artist VALUES (106, 'Rembrandt', 'NE')
INSERT INTO Artist VALUES (109, 'Ansel Adams', 'US')
INSERT INTO Artist VALUES (110, 'Francisco Goya', 'SP')
INSERT INTO Artist VALUES (113, 'Man Ray', 'US')
INSERT INTO Artist VALUES (127, 'Claude Monet', 'FR')
INSERT INTO Artist VALUES (130, 'Louise Bourgeois', 'FR')
INSERT INTO Artist VALUES (144, 'William Hogarth', 'UK')
INSERT INTO Artist VALUES (150, 'Edgar Degas', 'FR')
INSERT INTO Artist VALUES (154, 'Alberto Giacometti', 'SW')
INSERT INTO Artist VALUES (164, 'Leonardo da Vinci', 'IT')

INSERT INTO Employees VALUES (1032, 'James', 'Smith', 'DIR')
INSERT INTO Employees VALUES (1043, 'Carly', 'Vega', 'ED')
INSERT INTO Employees VALUES (1066, 'Leslie', 'Serrano', 'CUR')
INSERT INTO Employees VALUES (1071, 'Stacey', 'Vaugn', 'TG')
INSERT INTO Employees VALUES (1083, 'Cecil', 'Graham', 'INT')

INSERT INTO Artwork VALUES (201, 'The Apocalypse', 103, 'PR')
INSERT INTO Artwork VALUES (225, 'The Enraged Musician', 144, 'PR')
INSERT INTO Artwork VALUES (234, 'The Five Orders of Periwigs', 144, 'PR')
INSERT INTO Artwork VALUES (342, 'Portrait of a Man in Red Chalk', 164, 'D')
INSERT INTO Artwork VALUES (378, 'Worn Out', 102, 'D')
INSERT INTO Artwork VALUES (394, 'The Parsonage Garden at Nuenen in Winter', 102, 'D')
INSERT INTO Artwork VALUES (402, 'Annette', 154, 'S')
INSERT INTO Artwork VALUES (403, 'Spoon Woman', 154, 'S')
INSERT INTO Artwork VALUES (455, 'Bacchus', 101, 'S')
INSERT INTO Artwork VALUES (478, 'Little Dancer of Fourteen Years', 150, 'S')
INSERT INTO Artwork VALUES (486, 'Sleeping Figure', 130, 'S')
INSERT INTO Artwork VALUES (510, 'The Love Embrace of the Universe', 104, 'P')
INSERT INTO Artwork VALUES (523, 'Andromeda', 106, 'P')
INSERT INTO Artwork VALUES (546, 'Saturn Devouring His Son', 110, 'P')
INSERT INTO Artwork VALUES (550, 'The Magpie', 127, 'P')
INSERT INTO Artwork VALUES (572, 'Boulevard Saint-Denis, Argenteuil, in Winter', 127, 'P')
INSERT INTO Artwork VALUES (602, 'Ingress Violin', 113, 'PH')
INSERT INTO Artwork VALUES (615, 'Noire Et Blanche', 113, 'PH')
INSERT INTO Artwork VALUES (623, 'Moon Over Half Dome', 109, 'PH')
INSERT INTO Exhibit VALUES (101, 201, 1066)
INSERT INTO Exhibit VALUES (101, 455, 1066)
INSERT INTO Exhibit VALUES (101, 523, 1066)
INSERT INTO Exhibit VALUES (101, 546, 1066)
INSERT INTO Exhibit VALUES (101, 623, 1066)
INSERT INTO Exhibit VALUES (102, 225, 1083)
INSERT INTO Exhibit VALUES (102, 602, 1083)
INSERT INTO Exhibit VALUES (102, 478, 1083)
INSERT INTO Exhibit VALUES (103, 615, 1032)
INSERT INTO Exhibit VALUES (103, 234, 1032)
INSERT INTO Exhibit VALUES (103, 378, 1032)
INSERT INTO Exhibit VALUES (104, 510, 1043)
INSERT INTO Exhibit VALUES (104, 402, 1043)
INSERT INTO Exhibit VALUES (104, 403, 1043)
INSERT INTO Exhibit VALUES (105, 394, 1071)
INSERT INTO Exhibit VALUES (105, 342, 1071)
INSERT INTO Exhibit VALUES (105, 486, 1071) */
